INSERT IGNORE INTO `items` (`name`, `label`, `limit`, `weight`, `rare`, `can_remove`, `price`) 

VALUES 
('MCDS_BIG_BREAKFAST', 'McDonalds Big Breakfast', NULL, '1', '0', '1', '0'),
('MCDS_HOTCAKES', 'McDonalds Hotcakes', NULL, '1', '0', '1', '0'),
('MCDS_FRIES', 'McDonalds Fries', NULL, '1', '0', '1', '0'),
('MCDS_SAUSAGEMCMCUFFIN', 'Sausage & Egg McMuffin', NULL, '1', '0', '1', '0'), 
('MCDS_EGGMCMUFFIN', 'Egg McMuffin', NULL, '1', '0', '1', '0'),
('MCDS_CHEESEBURGER', 'Cheeseburger', NULL, '1', '0', '1', '0'),
('MCDS_BIGTASTY', 'Big Tasty Meal', NULL, '1', '0', '1', '0'),
('MCDS_MCROYALE', 'McRoyale Burger', NULL, '1', '0', '1', '0'),
('MCDS_QUARTERPOUNDER', 'Quarter Pounder', NULL, '1', '0', '1', '0'), 
('MCDS_BIGMAC', 'BigMac Meal', NULL, '1', '0', '1', '0'),
('MCDS_DBLCHEESEBURGER', 'Double Cheeseburger', NULL, '1', '0', '1', '0'),
('MCDS_BEEFBURGER', 'Beefburger', NULL, '1', '0', '1', '0'),
('MCDS_BBQANGUS', 'BBQ Angus Burger', NULL, '1', '0', '1', '0'), 
('MCDS_CHICKENMAC', 'Chicken Mac Meal', NULL, '1', '0', '1', '0'), 
('MCDS_MCNUGGETS', 'Chicken Nuggets', NULL, '1', '0', '1', '0'),
('MCDS_WRAP', 'BBQ Chicken Wrap', NULL, '1', '0', '1', '0'),
('MCDS_FILETOFISH', 'Filet-O-Fish', NULL, '1', '0', '1', '0'),
('MCDS_SPICYCHICK', 'Spicy Crunchy Chicken', NULL, '1', '0', '1', '0'),
('MCDS_MCFLURRY', 'McFlurry', NULL, '1', '0', '1', '0'),
('MCDS_COKE', 'Coke', NULL, '1', '0', '1', '0'),
('MCDS_ORANGE', 'Orange Juice', NULL, '1', '0', '1', '0'),
('MCDS_FANTA', 'Fanta', NULL, '1', '0', '1', '0'),
('MCDS_MILKSHAKE', 'MilkShake', NULL, '1', '0', '1', '0'),
('MCDS_COFFEE', 'Coffee', NULL, '1', '0', '1', '0'),
('MCDS_LATTE', 'Latte', NULL, '1', '0', '1', '0'),
('MCDS_AMERICANO', 'Americano', NULL, '1', '0', '1', '0'),
('MCDS_MOCHA', 'Mocha', NULL, '1', '0', '1', '0'),
('MCDS_HOTCHOC', 'Hot Chocolate', NULL, '1', '0', '1', '0'),
('MCDS_CHICKENSPECIAL', 'Grande Chicken Special', NULL, '1', '0', '1', '0');